### ISSUE TITLE
AttributeError: 'NpzFile' object has no attribute 'shape'

### ISSUE THREAD

**Issue by aloerch** [blackecho/Deep-Learning-TensorFlow#33]
Hello!

I've just started using yadlt, and am working with the github version, cloned 2 days ago. I'm loading my own dataset (.npz files) with the command_line/run_stacked_autoencoder_unsupervised.py model.
## Here's the error:

Training layer 1...
Traceback (most recent call last):
  File "command_line/run_stacked_autoencoder_unsupervised.py", line 185, in <module>
    encoded_X, encoded_vX = sdae.pretrain(trX, vlX)
  File "/usr/local/lib/python2.7/dist-packages/yadlt/models/autoencoder_models/deep_autoencoder.py", line 142, in pretrain
    validation_set=validation_set)
  File "/usr/local/lib/python2.7/dist-packages/yadlt/core/model.py", line 180, in pretrain_procedure
    layer_graphs[l])
  File "/usr/local/lib/python2.7/dist-packages/yadlt/core/model.py", line 196, in _pretrain_layer_and_gen_feed
    layer_obj.fit(train_set, validation_set, graph=graph)
  File "/usr/local/lib/python2.7/dist-packages/yadlt/core/unsupervised_model.py", line 44, in fit
    self.build_model(train_set.shape[1])
## AttributeError: 'NpzFile' object has no attribute 'shape'

The initial dataset is a bunch of 256x256 rgb images, and I saved them to npz as a
(21280, 256, 256, 3)
sized array. 

At the moment, I'm saving only 1 array in the npz file (not multiple arrays). 

I'm having difficulty figuring out how train_set has not attribute shape...

Thanks for your help!

**Comment by aloerch** [comment]
Ok, couple quick notes after further inspection:

1. The version I was using (pip) did not have many of the changes implemented 7-days ago, which I discovered when I abandoned trying to do the work on npz files in python 2.7 and moved to npy in python3. 

2. Npy data (rather than npz) loaded fine. I'm not sure still what the problem loading npz's was, or whether it was recently fixed, but npy's are OK. 

3. There is a new problem I've encountered, so I'm going to open a new issue for that.

**Comment by blackecho** [comment]
Yep, at the moment only npy files can be loaded. For [numpy docs](http://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html):

* If the file contains pickle data, then whatever object is stored in the pickle is returned.
* If the file is a .npy file, then a single array is returned.
* If the file is a .npz file, then a dictionary-like object is returned, containing {filename: array} key-value pairs, one for each file in the archive.

So the problem is that `load(npz)` does not return a numpy array directly, but an object, from which the data should be extracted. `load(npy)` instead loads directly a numpy array, with `shape` and the other methods. I should be easy to modify the function to support both .npz and .npy.
I'll close this once done with that.

**Comment by 13717630148** [comment]
can i ask a question:
when i use 'self.data_dict = np.load(vgg16_npy_path, encoding='latin1').item()'
it says:AttributeError: 'NpzFile' object has no attribute 'item'
thanks

**Comment by usernamenotavaila** [comment]
It works.Thank you very much for solving the problem.
